# Generated by Django 3.1.7 on 2021-08-17 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_phone_number', models.CharField(default='', max_length=15, verbose_name='연락처')),
                ('name', models.CharField(max_length=20)),
                ('is_agree_term', models.BooleanField(blank=True, default=False, verbose_name='동의 여부')),
                ('birth_day', models.CharField(blank=True, default='', max_length=10, verbose_name='생일')),
                ('mobile_phone_carrier', models.SmallIntegerField(blank=True, choices=[(0, None), (1, 'KT'), (2, 'SKT'), (3, 'LGU+'), (4, 'KT 알뜰폰'), (5, 'SKT 알뜰폰'), (6, 'LGU+ 알뜰폰')], default=None, null=True, verbose_name='통신사')),
                ('phone_number', models.CharField(blank=True, default='', max_length=15, verbose_name='전화번호')),
                ('address', models.CharField(blank=True, default='', max_length=100, verbose_name='주소')),
                ('job', models.CharField(blank=True, default='', max_length=20, verbose_name='직업')),
                ('is_drive', models.BooleanField(blank=True, default=None, null=True, verbose_name='운전여부')),
                ('memo', models.TextField(blank=True, default='', verbose_name='메모')),
                ('email', models.CharField(blank=True, default='', max_length=50, verbose_name='이메일')),
                ('company', models.CharField(blank=True, default='', max_length=100, verbose_name='회사명')),
                ('drink_bottle', models.SmallIntegerField(blank=True, default=0, verbose_name='음주 병수')),
                ('drink_week', models.SmallIntegerField(blank=True, default=0, verbose_name='음주 한주 횟수')),
                ('smoke_daily', models.SmallIntegerField(blank=True, default=0, verbose_name='흡연 일일 횟수')),
                ('smoke_years', models.SmallIntegerField(blank=True, default=0, verbose_name='흡연 년수')),
                ('height', models.SmallIntegerField(blank=True, default=0, verbose_name='키')),
                ('weight', models.SmallIntegerField(blank=True, default=0, verbose_name='몸무게')),
                ('baby_due_date', models.CharField(blank=True, default='', max_length=10, verbose_name='출산 에정일')),
                ('relate_name', models.CharField(blank=True, default='', max_length=10, verbose_name='관계')),
                ('legal_representative_name', models.CharField(blank=True, default='', max_length=5, verbose_name='법정 대리인')),
                ('user_view_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_customers', models.ManyToManyField(blank=True, related_name='_customer_group_customers_+', to='customers.Customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '고객',
                'verbose_name_plural': '고객',
            },
        ),
        migrations.CreateModel(
            name='CustomerMedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_inpatient', models.BooleanField(verbose_name='입원여부')),
                ('diagnostic_name', models.CharField(max_length=100, verbose_name='진단명')),
                ('treatment_content', models.CharField(max_length=100, verbose_name='치료 내용')),
                ('hospital_name', models.CharField(blank=True, default='', max_length=100, verbose_name='병원명')),
                ('treatment_start_date', models.CharField(blank=True, default='', max_length=10, verbose_name='치료 시작일')),
                ('treatment_end_date', models.CharField(blank=True, default='', max_length=10, verbose_name='치료 종료일')),
                ('is_recurrence', models.BooleanField(blank=True, default=None, null=True, verbose_name='재발여부')),
                ('is_cure', models.BooleanField(blank=True, default=None, null=True, verbose_name='완치여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_histories', to='customers.customer')),
            ],
            options={
                'verbose_name': '고객 병력',
                'verbose_name_plural': '고객 병력',
            },
        ),
    ]
