# Generated by Django 3.1.7 on 2021-08-18 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='group_customers',
        ),
        migrations.AddField(
            model_name='customer',
            name='group_customers',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_group_customers', to='customers.customer'),
        ),
    ]
