# Generated by Django 3.1.7 on 2021-08-18 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210818_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='group_customers',
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_customers', to='customers.customer')),
                ('parent_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_customers', to='customers.customer')),
            ],
            options={
                'verbose_name': '고객 그룹',
                'verbose_name_plural': '고객 그룹',
            },
        ),
    ]
