# Generated by Django 3.1.7 on 2021-09-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20210827_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_drive',
        ),
        migrations.AddField(
            model_name='customer',
            name='drive_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, None), (1, '자가용'), (2, '영업용'), (3, '비운전자')], default=None, null=True, verbose_name='운전여부'),
        ),
    ]
