# Generated by Django 3.1.7 on 2021-09-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20210909_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='business_type',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='업종'),
        ),
    ]
