# Generated by Django 3.1.7 on 2021-08-17 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.SmallIntegerField(choices=[(1, '생명보험'), (2, '손해보험')], default=1)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='상품명')),
                ('contractor_name', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='계약자 이름')),
                ('insured_name', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='피보험자 이름')),
                ('is_same_insured', models.BooleanField(blank=True, default=None, null=True, verbose_name='계/피 동일')),
                ('portfolio_type', models.SmallIntegerField(choices=[(1, '기존'), (2, '제안')], default=1, verbose_name='포트폴리오 타입')),
                ('payment_period_type', models.SmallIntegerField(choices=[(1, '년'), (2, '년 갱신')], default=1, verbose_name='납입기간 타입')),
                ('payment_period', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='납입기간')),
                ('warranty_period_type', models.SmallIntegerField(choices=[(1, '세 만기'), (2, '년 만기'), (3, '종신')], default=1, verbose_name='보장기간 타입')),
                ('warranty_period', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='보장기간')),
                ('contract_date', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='계약일')),
                ('expiry_date', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='만기일')),
                ('renewal_month', models.IntegerField(blank=True, default=None, null=True, verbose_name='총 갱신 납입 회차')),
                ('non_renewal_month', models.IntegerField(blank=True, default=None, null=True, verbose_name='총 비갱신 납입 회차')),
                ('monthly_assurance_premium', models.IntegerField(blank=True, default=None, null=True, verbose_name='월 보장 보험료')),
                ('monthly_special_premium', models.IntegerField(blank=True, default=None, null=True, verbose_name='월 특약 보험료')),
                ('monthly_premiums', models.IntegerField(blank=True, default=None, null=True, verbose_name='월 납입 보험료')),
                ('monthly_contract_premium', models.IntegerField(blank=True, default=None, null=True, verbose_name='월 주계약 보험료')),
                ('monthly_earned_premium', models.IntegerField(blank=True, default=None, null=True, verbose_name='월 적립 보험료')),
                ('monthly_non_renewal_premium', models.IntegerField(blank=True, default=None, null=True, verbose_name='월 비갱신 보험료')),
                ('monthly_renewal_premium', models.IntegerField(blank=True, default=None, null=True, verbose_name='월 갱신 보험료')),
                ('total_premiums', models.IntegerField(blank=True, default=None, null=True, verbose_name='총 납입 보험료')),
                ('total_renewal_premium', models.IntegerField(blank=True, default=None, null=True, verbose_name='총 갱신 보험료')),
                ('total_non_renewal_premium', models.IntegerField(blank=True, default=None, null=True, verbose_name='총 비갱신 보험료')),
                ('total_earned_premium', models.IntegerField(blank=True, default=None, null=True, verbose_name='총 적립 보험료')),
                ('cancellation_refund', models.IntegerField(blank=True, default=None, null=True, verbose_name='혜약 환급금')),
                ('refund_type', models.SmallIntegerField(choices=[(1, '세 만기'), (2, '년 만기'), (3, '종신')], default=1, verbose_name='환급타입')),
                ('percent_cancellation_refund', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='혜약 환급금 퍼센트')),
                ('renewal_growth_rate', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='갱신 증가율')),
                ('renewal_special_expiry_date', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='갱신특약 만기일')),
                ('user_view_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='customer_insurance_list', to='customers.customer')),
            ],
            options={
                'verbose_name': '고객 보험',
                'verbose_name_plural': '고객 보험',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='보험명')),
                ('order', models.SmallIntegerField(blank=True, default=0, verbose_name='순서')),
                ('image', imagekit.models.fields.ProcessedImageField(default='', upload_to='uploads/insurance/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': '보험',
                'verbose_name_plural': '보험',
            },
        ),
        migrations.CreateModel(
            name='InsuranceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.SmallIntegerField(choices=[(0, '공통'), (1, '생명보험'), (2, '손해보험')], default=0)),
                ('name', models.CharField(max_length=20)),
                ('order', models.SmallIntegerField(blank=True, default=0, verbose_name='순서')),
            ],
            options={
                'verbose_name': '보험 카테고리',
                'verbose_name_plural': '보험 카테고리',
            },
        ),
        migrations.CreateModel(
            name='InsuranceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('order', models.SmallIntegerField(blank=True, default=0, verbose_name='순서')),
            ],
            options={
                'verbose_name': '보험 상세 아이템',
                'verbose_name_plural': '보험 상세 아이템',
            },
        ),
        migrations.CreateModel(
            name='InsuranceTag',
            fields=[
                ('name', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '보험 태그',
                'verbose_name_plural': '보험 태그',
            },
        ),
        migrations.CreateModel(
            name='InsuranceTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.SmallIntegerField(choices=[(1, '생명보험'), (2, '손해보험')], default=1)),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
                ('payment_period_type', models.SmallIntegerField(choices=[(1, '년'), (2, '년 갱신')], default=1, verbose_name='납입기간 타입')),
                ('payment_period', models.SmallIntegerField(verbose_name='납입기간')),
                ('warranty_period_type', models.SmallIntegerField(choices=[(1, '세 만기'), (2, '년 만기'), (3, '종신')], default=1, verbose_name='보장기간 타입')),
                ('warranty_period', models.SmallIntegerField(verbose_name='보장기간')),
                ('old', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='나이')),
                ('expiry_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='만기일')),
                ('monthly_premiums', models.IntegerField(blank=True, default=None, null=True, verbose_name='월 납입 보험료')),
                ('monthly_assurance_premium', models.IntegerField(blank=True, default=None, null=True, verbose_name='월 보장 보험료')),
                ('monthly_contract_premium', models.IntegerField(blank=True, default=None, null=True, verbose_name='월 주계약 보험료')),
                ('monthly_renewal_premium', models.IntegerField(blank=True, default=None, null=True, verbose_name='월 갱신 보험료')),
                ('monthly_special_premium', models.IntegerField(blank=True, default=None, null=True, verbose_name='월 특약 보험료')),
                ('monthly_earned_premium', models.IntegerField(blank=True, default=None, null=True, verbose_name='월 적립 보험료')),
                ('refund_type', models.SmallIntegerField(choices=[(1, '세 만기'), (2, '년 만기'), (3, '종신')], default=1, verbose_name='환급타입')),
                ('monthly_non_renewal_premium', models.IntegerField(blank=True, default=None, null=True, verbose_name='월 비갱신 보험료')),
                ('total_premiums', models.IntegerField(blank=True, default=None, null=True, verbose_name='총 납입 보험료')),
                ('total_renewal_premium', models.IntegerField(blank=True, default=None, null=True, verbose_name='총 갱신 보험료')),
                ('total_non_renewal_premium', models.IntegerField(blank=True, default=None, null=True, verbose_name='총 비갱신 보험료')),
                ('total_earned_premium', models.IntegerField(blank=True, default=None, null=True, verbose_name='총 적립 보험료')),
                ('renewal_growth_rate', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='갱신 증가율')),
                ('user_view_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurances.insurance')),
                ('tags', models.ManyToManyField(blank=True, to='insurances.InsuranceTag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '보험 템플릿',
                'verbose_name_plural': '보험 템플릿',
            },
        ),
        migrations.CreateModel(
            name='InsuranceTemplateDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('assurance_amount', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('payment_period_type', models.SmallIntegerField(blank=True, choices=[(1, '세'), (2, '년'), (3, '년 갱신')], default=1)),
                ('payment_period', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('warranty_period_type', models.SmallIntegerField(blank=True, choices=[(1, '세'), (2, '년'), (3, '날짜'), (4, '종신')], default=1)),
                ('warranty_period', models.CharField(max_length=20)),
                ('total_renewal_premium', models.IntegerField(blank=True, default=None, null=True, verbose_name='총 갱신 보험료')),
                ('total_non_renewal_premium', models.IntegerField(blank=True, default=None, null=True, verbose_name='총 비갱신 보험료')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detail', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurances.insurancedetail')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_list', to='insurances.insurancetemplate')),
            ],
            options={
                'verbose_name': '보험 템플릿 상세',
                'verbose_name_plural': '보험 템플릿 상세',
            },
        ),
        migrations.CreateModel(
            name='InsuranceSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.SmallIntegerField(choices=[(0, '공통'), (1, '생명보험'), (2, '손해보험')], default=0)),
                ('name', models.CharField(max_length=20)),
                ('order', models.SmallIntegerField(blank=True, default=0, verbose_name='순서')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='insurances.insurancecategory')),
            ],
            options={
                'verbose_name': '보험 서브 카테고리',
                'verbose_name_plural': '보험 서브 카테고리',
            },
        ),
        migrations.AddField(
            model_name='insurancedetail',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='insurances.insurancesubcategory'),
        ),
        migrations.CreateModel(
            name='CustomerInsuranceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assurance_amount', models.SmallIntegerField(verbose_name='보장 금액')),
                ('premium', models.SmallIntegerField(verbose_name='보험료')),
                ('payment_period_type', models.SmallIntegerField(choices=[(1, '년'), (2, '세'), (3, '년 갱신')], default=1, verbose_name='납입기간 타입')),
                ('payment_period', models.SmallIntegerField(verbose_name='납입기간')),
                ('warranty_period_type', models.SmallIntegerField(choices=[(1, '세'), (2, '년'), (3, '날짜'), (4, '종신')], default=1, verbose_name='보증기간 타입')),
                ('warranty_period', models.CharField(max_length=20, verbose_name='보증기간')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurances.insurancedetail')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_list', to='insurances.customerinsurance')),
            ],
            options={
                'verbose_name': '고객 보험 상세',
                'verbose_name_plural': '고객 보험 상세',
            },
        ),
        migrations.AddField(
            model_name='customerinsurance',
            name='insurance',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurances.insurance'),
        ),
        migrations.AddField(
            model_name='customerinsurance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
