# Generated by Django 3.1.7 on 2021-08-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinsurancedetail',
            name='total_non_renewal_premium',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='총 비갱신 보험료'),
        ),
        migrations.AddField(
            model_name='customerinsurancedetail',
            name='total_renewal_premium',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='총 갱신 보험료'),
        ),
    ]
