# Generated by Django 3.1.7 on 2021-08-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0004_insurancedetail_chart_based_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancedetail',
            name='chart_type',
            field=models.SmallIntegerField(choices=[(1, '사후진운기'), (2, '실손의료비')], default=1),
        ),
    ]
