# Generated by Django 3.1.7 on 2021-08-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0005_insurancedetail_chart_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinsurance',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
