# Generated by Django 3.1.7 on 2021-08-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0006_customerinsurance_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinsurance',
            name='comment_title',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
