# Generated by Django 3.1.7 on 2021-09-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0008_auto_20210827_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancetemplate',
            name='is_common',
            field=models.BooleanField(default=False, verbose_name='공통 유무'),
        ),
    ]
