# Generated by Django 3.1.7 on 2021-09-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0010_insurance_insurance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancetemplate',
            name='warranty_period',
            field=models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='보장기간'),
        ),
        migrations.AlterField(
            model_name='insurancetemplatedetail',
            name='warranty_period',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
