# Generated by Django 3.1.7 on 2021-09-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0013_auto_20210915_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinsurance',
            name='expected_due_year',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='예상 만기 년수'),
        ),
        migrations.AddField(
            model_name='customerinsurance',
            name='is_common',
            field=models.BooleanField(default=False, verbose_name='공통 유무'),
        ),
        migrations.AddField(
            model_name='customerinsurance',
            name='old',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='나이'),
        ),
    ]
