# Generated by Django 3.1.7 on 2021-09-24 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_business_type'),
        ('insurances', '0014_auto_20210925_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinsurance',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_insurance_list', to='customers.customer'),
        ),
    ]
