# Generated by Django 3.1.7 on 2021-09-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0016_auto_20210926_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.SmallIntegerField(choices=[(1, 'Cart1'), (2, 'Cart2')], default=1)),
                ('name', models.CharField(max_length=20)),
                ('order', models.SmallIntegerField(blank=True, default=0, verbose_name='순서')),
                ('chart_based_amount', models.SmallIntegerField(blank=True, default=0, verbose_name='차트 기준 금액')),
            ],
            options={
                'verbose_name': '분석 상세 아이템',
                'verbose_name_plural': '분석 상세 아이템',
            },
        ),
        migrations.AddField(
            model_name='insurancedetail',
            name='analysis_detail',
            field=models.ManyToManyField(to='insurances.AnalysisDetail'),
        ),
        migrations.AddField(
            model_name='insurancedetail',
            name='chart_detail',
            field=models.ManyToManyField(to='insurances.ChartDetail'),
        ),
    ]
