# Generated by Django 3.1.7 on 2021-09-26 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0017_auto_20210926_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartdetail',
            options={'verbose_name': '분석 차트 아이템', 'verbose_name_plural': '분석 차트 아이템'},
        ),
        migrations.RemoveField(
            model_name='analysisdetail',
            name='chart_type',
        ),
    ]
