# Generated by Django 3.1.7 on 2021-09-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0020_auto_20210927_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinsurance',
            name='renewal_special_expiry',
            field=models.IntegerField(blank=True, default=None, max_length=10, null=True, verbose_name='갱신특약 만기일'),
        ),
    ]
