# Generated by Django 3.1.7 on 2021-09-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0021_customerinsurance_renewal_special_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinsurance',
            name='renewal_special_expiry',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='갱신특약 만기일'),
        ),
    ]
