# Generated by Django 3.1.7 on 2021-09-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0022_auto_20210927_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinsurance',
            name='renewal_special_expiry_date',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='갱신특약 만기일 날짜'),
        ),
        migrations.AlterField(
            model_name='customerinsurance',
            name='total_earned_premium',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='총 적립 보험료'),
        ),
        migrations.AlterField(
            model_name='customerinsurance',
            name='total_non_renewal_premium',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='총 비갱신 보험료'),
        ),
        migrations.AlterField(
            model_name='customerinsurance',
            name='total_premiums',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='총 납입 보험료'),
        ),
        migrations.AlterField(
            model_name='customerinsurance',
            name='total_renewal_premium',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='총 갱신 보험료'),
        ),
        migrations.AlterField(
            model_name='customerinsurancedetail',
            name='total_non_renewal_premium',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='총 비갱신 보험료'),
        ),
        migrations.AlterField(
            model_name='customerinsurancedetail',
            name='total_renewal_premium',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='총 갱신 보험료'),
        ),
    ]
