# Generated by Django 3.1.7 on 2021-10-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0023_auto_20210928_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinsurance',
            name='tags',
            field=models.ManyToManyField(blank=True, to='insurances.InsuranceTag'),
        ),
    ]
