# Generated by Django 3.1.7 on 2021-10-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0024_customerinsurance_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinsurance',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
