# Generated by Django 3.1.7 on 2024-02-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0025_customerinsurance_is_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_content', models.TextField(max_length=500)),
            ],
        ),
    ]
