# Generated by Django 3.1.7 on 2021-08-27 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('month_amount', models.SmallIntegerField(default=0)),
                ('sale', models.SmallIntegerField(default=0)),
                ('color', models.CharField(blank=True, default='', max_length=10)),
                ('expiry_month', models.SmallIntegerField()),
                ('order', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '멤버십',
                'verbose_name_plural': '멤버십',
            },
        ),
        migrations.CreateModel(
            name='MembershipPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('status', models.SmallIntegerField(choices=[(-1, 'READY'), (-2, 'CANCELED'), (-3, 'FAILED'), (-4, 'REFUNDED'), (1, 'PAID')], default=-1)),
                ('status_message', models.CharField(blank=True, default='', max_length=200)),
                ('payment_method', models.CharField(blank=True, choices=[('card', 'CARD'), ('trans', 'TRANS'), ('phone', 'PHONE')], default='', max_length=20)),
                ('card_number', models.CharField(blank=True, default='', max_length=20)),
                ('card_name', models.CharField(blank=True, default='', max_length=10)),
                ('card_option', models.CharField(blank=True, default='', max_length=20)),
                ('merchant_uid', models.CharField(max_length=255, unique=True)),
                ('pg', models.CharField(blank=True, default='NICE', max_length=20)),
                ('tid', models.CharField(blank=True, default='', max_length=100)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('is_sale', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voca_payments', to='membership.membership')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voca_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '결제내역',
                'verbose_name_plural': '결제내역',
            },
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('expiry_at', models.DateTimeField()),
                ('is_churned', models.BooleanField(default=False)),
                ('is_send_done_message', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.membership')),
                ('membership_payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.membershippayment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '유저 멤버십',
                'verbose_name_plural': '유저 멤버십',
            },
        ),
    ]
