# Generated by Django 3.1.7 on 2021-08-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='color',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='expiry_month',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='month_amount',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='membershippayment',
            name='buyer_email',
        ),
        migrations.RemoveField(
            model_name='membershippayment',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='membershippayment',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='membershippayment',
            name='card_option',
        ),
        migrations.RemoveField(
            model_name='membershippayment',
            name='is_sale',
        ),
        migrations.RemoveField(
            model_name='membershippayment',
            name='merchant_uid',
        ),
        migrations.RemoveField(
            model_name='membershippayment',
            name='pg',
        ),
        migrations.RemoveField(
            model_name='membershippayment',
            name='tid',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='is_send_done_message',
        ),
        migrations.AddField(
            model_name='membership',
            name='is_recommend',
            field=models.BooleanField(default=False, verbose_name='추천 유무'),
        ),
        migrations.AddField(
            model_name='membership',
            name='period_month',
            field=models.SmallIntegerField(default=0, verbose_name='멤버십 기간 개월수'),
        ),
        migrations.AddField(
            model_name='membership',
            name='product_amount',
            field=models.SmallIntegerField(default=0, verbose_name='멤버십 가격'),
        ),
        migrations.AddField(
            model_name='membership',
            name='sale_percent',
            field=models.SmallIntegerField(default=0, verbose_name='세일 퍼센트'),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='payment_username',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='임급자명'),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='결제링크수신번호'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='name',
            field=models.CharField(max_length=100, verbose_name='멤버십 이름'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='order',
            field=models.SmallIntegerField(verbose_name='순서 (낮은 순)'),
        ),
        migrations.AlterField(
            model_name='membershippayment',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='결제 가격'),
        ),
        migrations.AlterField(
            model_name='membershippayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[(1, '계좌'), (2, '논PG')], default='', max_length=20, verbose_name='결제 수단'),
        ),
        migrations.AlterField(
            model_name='membershippayment',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'READY'), (-2, 'CANCELED'), (-3, 'FAILED'), (-4, 'REFUNDED'), (1, 'PAID')], default=-1, verbose_name='결제 상태'),
        ),
        migrations.AlterField(
            model_name='membershippayment',
            name='status_message',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='결제 상태 메시지'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='expiry_at',
            field=models.DateTimeField(verbose_name='만료일'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='is_churned',
            field=models.BooleanField(default=False, verbose_name='환불유무'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='started_at',
            field=models.DateTimeField(verbose_name='시작일'),
        ),
    ]
