# Generated by Django 3.1.7 on 2021-08-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_auto_20210827_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershippayment',
            name='status_message',
        ),
        migrations.AlterField(
            model_name='membershippayment',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, '대기'), (-2, '취소'), (-3, '실패'), (-4, '환불'), (1, '결제')], default=-1, verbose_name='결제 상태'),
        ),
    ]
