# Generated by Django 3.1.7 on 2021-08-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_auto_20210827_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershippayment',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(1, '계좌'), (2, '논PG')], default=1, verbose_name='결제 수단'),
        ),
    ]
