# Generated by Django 3.1.7 on 2021-08-31 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0007_remove_usermembership_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='무료유무'),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='recommend_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommend_user_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
