# Generated by Django 3.1.7 on 2021-05-13 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_betauser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betauser',
            name='user',
        ),
        migrations.AddField(
            model_name='betauser',
            name='phone_number',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.phonenumber'),
        ),
        migrations.AddField(
            model_name='phonenumberuserprofile',
            name='is_agree_marketing',
            field=models.BooleanField(default=False),
        ),
    ]
