# Generated by Django 3.1.7 on 2021-05-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210514_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_agree_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_super',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PhoneNumberUserProfile',
        ),
    ]
