# Generated by Django 3.1.7 on 2021-05-30 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210514_1254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BetaUser',
        ),
    ]
