# Generated by Django 3.1.7 on 2021-06-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210602_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_first_visit',
            field=models.BooleanField(default=True),
        ),
    ]
