# Generated by Django 3.1.7 on 2021-08-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210619_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recommend_code',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
