# Generated by Django 3.1.7 on 2021-08-31 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_auto_20210830_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommend_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommend_me_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommend_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '추천인',
                'verbose_name_plural': '추천인',
            },
        ),
    ]
